site_name: Genomic Report
nav:
  - Home: index.md
  - Reference:
      - genomic_report.main: reference/genomic_report/main.md
      - genomic_report.annotate: reference/genomic_report/annotate.md
      - genomic_report.ipr: reference/genomic_report/ipr.md
      - genomic_report.inputs: reference/genomic_report/inputs.md
theme:
  name: "material"
repo_url: https://svn.bcgsc.ca/bitbucket/projects/SDEV/repos/genomic_report
repo_name: Bitbucket
site_dir: build-docs